version: '2'

services:

  apache:
    image: 'httpd'
    depends_on:
      - app
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./apache/httpd.conf:/usr/local/apache2/conf/httpd.conf:ro
      - ./apache/certs/Server.crt:/usr/local/apache2/conf/server.crt
      - ./apache/certs/Server.key:/usr/local/apache2/conf/server.key
    tty: true

  app:
    image: server
    build:
      context: .
    depends_on:
      - database
    command: "yarn start"
    # ports:
      # - 3000:3000
    expose:
      - 3000
    volumes:
      - ./:/usr/src/app:ro
      - yarn:/home/node/.cache/yarn
    tty: true
    environment: 
      DB_USERNAME: express
      DB_PASSWORD: test
      DB_NAME: express
      DB_HOSTNAME: database
      SECRET: lolthisisverysecret
      NODE_ENV: development
      WAIT_HOSTS: database:5432

  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: test 
      POSTGRES_USER: express
      POSTGRES_DB: express
    expose:
      - 5432
    tty: true
    # only for debug puropses
    ports:
      - 5432:5432

volumes:
  node_modules:
  yarn: